package se.liu.ida.retriever.vocabulary;

/* CVS $Id: $ */

import org.apache.jena.rdf.model.*;

/**
 * Vocabulary definitions from vocals.ttl
 * 
 * @author Auto-generated by schemagen on 29 Sep 2025 11:39
 */
public class Vocals {
	/**
	 * <p>
	 * The RDF model that holds the vocabulary terms
	 * </p>
	 */
	private static final Model M_MODEL = ModelFactory.createDefaultModel();

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 */
	public static final String NS = "http://w3id.org/rsp/vocals#";

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 * 
	 * @return namespace as String
	 * @see #NS
	 */
	public static String getURI() {
		return NS;
	}

	/**
	 * <p>
	 * The namespace of the vocabulary as a resource
	 * </p>
	 */
	public static final Resource NAMESPACE = M_MODEL.createResource(NS);

	/**
	 * <p>
	 * The ontology's owl:versionInfo as a string
	 * </p>
	 */
	public static final String VERSION_INFO = "0.1.1";

	/**
	 * <p>
	 * A relationship between a Stream and a StreamEndpoint. A stream may have
	 * several
	 * endpoints through which its contents can be accessible.
	 * </p>
	 */
	public static final Property hasEndpoint = M_MODEL.createProperty("http://w3id.org/rsp/vocals#hasEndpoint");

	/**
	 * <p>
	 * A relationship between a Stream and a partition, or portion of elements
	 * streamed
	 * </p>
	 */
	public static final Property hasPartition = M_MODEL.createProperty("http://w3id.org/rsp/vocals#hasPartition");

	/**
	 * <p>
	 * Relationship between a stream partition and the previous partition in the
	 * stream. it connects stream partitions in order
	 * </p>
	 */
	public static final Property previous = M_MODEL.createProperty("http://w3id.org/rsp/vocals#previous");

	/**
	 * <p>
	 * A stream composed of RDF data elements, i.e. RDF graphs and/or triples.
	 * </p>
	 */
	public static final Resource RDFStream = M_MODEL.createResource("http://w3id.org/rsp/vocals#RDFStream");

	/**
	 * <p>
	 * A potentially infinite sequence of data elements. A stream may be findable
	 * and accesible on the Web.
	 * </p>
	 */
	public static final Resource Stream = M_MODEL.createResource("http://w3id.org/rsp/vocals#Stream");

	/**
	 * <p>
	 * A Stream Descriptor is a Web document that contains the description of a
	 * Stream.
	 * </p>
	 */
	public static final Resource StreamDescriptor = M_MODEL
			.createResource("http://w3id.org/rsp/vocals#StreamDescriptor");

	/**
	 * <p>
	 * Represents a specific available form of a stream. Each stream might be
	 * available
	 * in different forms, these forms might represent different access points of
	 * the stream. Examples of distributions include a WebSocket endpoint, an HTTP
	 * endpoint, a Server-Sent Events endpoint, MQTT, etc.
	 * </p>
	 */
	public static final Resource StreamDistribution = M_MODEL
			.createResource("http://w3id.org/rsp/vocals#StreamDistribution");

	/**
	 * <p>
	 * Represents a specific available form of a stream. Each stream might be
	 * available
	 * in different forms, these forms might represent different access points of
	 * the stream. Examples of endpoints include a WebSocket endpoint, an HTTP
	 * endpoint,
	 * a Server-Sent Events endpoint, MQTT, etc.
	 * </p>
	 */
	public static final Resource StreamEndpoint = M_MODEL.createResource("http://w3id.org/rsp/vocals#StreamEndpoint");

	/**
	 * <p>
	 * A finite subset of the stream that are made available to be accessed and
	 * consumed
	 * by standard Linked Data services.
	 * </p>
	 */
	public static final Resource StreamPartition = M_MODEL.createResource("http://w3id.org/rsp/vocals#StreamPartition");

	/**
	 * <p>
	 * Esta ontología has sido diseñada para representar Streams de datos en RDF,
	 * así como los endpoints a través de los cuales se puede acceder a los datos
	 * de estos streams; y los meta datos correspondientes.Cette ontologie a été
	 * conçue pour representer des données et meta-données de streams RDF, ainsi
	 * que leurs points d'accès.This ontology aims to model RDF streams, their
	 * metadata,
	 * and access endpoints for publishing and consuming these streams
	 * </p>
	 */
	public static final Resource __ = M_MODEL.createResource("http://w3id.org/rsp/vocals#");

}
